apiVersion: v1
kind: Service
metadata:
  name: {{ template "bitcoind.fullname" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
    - name: testnet
      port: {{ .Values.service.testnetPort }}
      targetPort: testnet
    - name: testnetp2p
      port: {{ .Values.service.testnetP2pPort }}
      targetPort: testnetp2pport
    - port: 3000
      targetPort: http
      protocol: TCP
      name: electrs-mainnet
    - port: 3001
      targetPort: http
      protocol: TCP
      name: electrs-testnet
    - port: {{ int .Values.metrics.port }}
      targetPort: exporter
      protocol: TCP
      name: metrics
  selector:
    app: {{ template "bitcoind.name" . }}
    release: {{ .Release.Name }}
