apiVersion: v1
kind: Service
metadata:
  name: {{ template "bitcoind.fullname" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
      {{- if .Values.electrs.enabled }}
    - port: 3000
      targetPort: http
      protocol: TCP
      name: electrs-mainnet
    - port: 3001
      targetPort: http
      protocol: TCP
      name: electrs-testnet
      {{- end }}
      {{- if .Values.metrics.enabled }}
    - port: {{ int .Values.metrics.port }}
      targetPort: exporter
      protocol: TCP
      name: metrics
      {{- end }}
  selector:
    app: {{ template "bitcoind.name" . }}
    release: {{ .Release.Name }}
