apiVersion: v1
kind: Service
metadata:
  name: {{ template "bitcoind.fullname" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
    - name: testnet
      port: {{ .Values.service.testnetPort }}
    - name: testnetp2p
      port: {{ .Values.service.testnetP2pPort }}
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: electrs-mainnet
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: electrs-testnet
  selector:
    app: {{ template "bitcoind.name" . }}
    release: {{ .Release.Name }}
