---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-rpc
spec:
  ports:
  - port: 9933
    name: http-rpc
  - port: 9944
    name: websocket-rpc
  selector:
    app: {{ .Values.GitlabEnvSlug | default .Values.app }}
  sessionAffinity: None
  type: ClusterIP
  clusterIP: None

