apiVersion: v1
entries:
  postgres-operator:
  - apiVersion: v1
    appVersion: 1.6.1
    created: "2021-02-19T12:13:13.262839018+01:00"
    description: Postgres Operator creates and manages PostgreSQL clusters running in Kubernetes
    digest: 4ba5972cd486dcaa2d11c5613a6f97f6b7b831822e610fe9e10a57ea1db23556
    home: https://github.com/zalando/postgres-operator
    keywords:
    - postgres
    - operator
    - cloud-native
    - patroni
    - spilo
    maintainers:
    - email: opensource@zalando.de
      name: Zalando
    name: postgres-operator
    sources:
    - https://github.com/zalando/postgres-operator
    urls:
    - postgres-operator-1.6.1.tgz
    version: 1.6.1
  - apiVersion: v1
    appVersion: 1.6.0
    created: "2021-02-19T12:13:13.260413425+01:00"
    description: Postgres Operator creates and manages PostgreSQL clusters running in Kubernetes
    digest: 1b4c3892335a207f4719c3817186e98b6105398ab45dafc4274dac837ec9bf31
    home: https://github.com/zalando/postgres-operator
    keywords:
    - postgres
    - operator
    - cloud-native
    - patroni
    - spilo
    maintainers:
    - email: opensource@zalando.de
      name: Zalando
    name: postgres-operator
    sources:
    - https://github.com/zalando/postgres-operator
    urls:
    - postgres-operator-1.6.0.tgz
    version: 1.6.0
  - apiVersion: v1
    appVersion: 1.5.0
    created: "2021-02-19T12:13:13.257505579+01:00"
    description: Postgres Operator creates and manages PostgreSQL clusters running in Kubernetes
    digest: 198351d5db52e65cdf383d6f3e1745d91ac1e2a01121f8476f8b1be728b09531
    home: https://github.com/zalando/postgres-operator
    keywords:
    - postgres
    - operator
    - cloud-native
    - patroni
    - spilo
    maintainers:
    - email: opensource@zalando.de
      name: Zalando
    name: postgres-operator
    sources:
    - https://github.com/zalando/postgres-operator
    urls:
    - postgres-operator-1.5.0.tgz
    version: 1.5.0
generated: "2021-02-19T12:13:13.25598107+01:00"
