apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "interlay-firesquid.fullname" . }}-gateway
  labels:
    {{- include "interlay-firesquid.labels" . | nindent 4 }}
    app.kubernetes.io/component: substrate-gateway
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "interlay-firesquid.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: substrate-gateway
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "interlay-firesquid.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: substrate-gateway
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "interlay-firesquid.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: gateway
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.gateway.image }}"
          imagePullPolicy: {{ .Values.gateway.imagePullPolicy }}
          {{- with .Values.gateway.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          {{- with .Values.gateway.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
