---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "interlay-firesquid.fullname" . }}-query-node
  labels:
    {{- include "interlay-firesquid.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "interlay-firesquid.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: substrate-query-node
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "interlay-firesquid.fullname" . }}-gateway
  labels:
    {{- include "interlay-firesquid.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "interlay-firesquid.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: substrate-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "interlay-firesquid.fullname" . }}-explorer
  labels:
    {{- include "interlay-firesquid.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "interlay-firesquid.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: substrate-explorer
