{{- if .Values.activateKeysJob.enabled -}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: deployment-restart
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restart
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["statefulsets"]
    resourceNames: [{{ include "polkabtc.fullname" . | quote }}]
    verbs: ["get", "patch", "list", "watch"]
---
# bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-restart
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-restart
subjects:
  - kind: ServiceAccount
    name: deployment-restart
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "polkabtc.fullname" . }}-restart-node
  labels:
    {{- include "polkabtc.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: deployment-restart
      restartPolicy: Never
      containers:
        - name: kubectl
          image: bitnami/kubectl
          command:
            - 'kubectl'
            - 'rollout'
            - 'restart'
            - 'statefulset/{{ include "polkabtc.fullname" . }}'
{{- end }}