apiVersion: v1
kind: Service
metadata:
  name: {{ include "polkabtc.fullname" . }}-rpc
  labels:
    {{- include "polkabtc.labels" . | nindent 4 }}
spec:
  ports:
    - port: 9933
      name: http-rpc
    - port: 9944
      name: websocket-rpc
      protocol: TCP
  selector:
    {{- include "polkabtc.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
{{- if .Values.nodePortEnabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "polkabtc.fullname" . }}-p2p
  labels:
    {{- include "polkabtc.labels" . | nindent 4 }}
spec:
  externalTrafficPolicy: Local
  ports:
  - port: {{ .Values.p2pPort }}
    name: p2p
    nodePort: {{ .Values.p2pPort }}
  selector:
    {{- include "polkabtc.selectorLabels" . | nindent 4 }}
  type: NodePort
  {{- end }}
