apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "polkadot-deployer.podRestarterName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "polkadot-deployer.podRestarterName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "polkadot-deployer.sessionInjectionName" . }}
- kind: ServiceAccount
  name: {{ include "polkadot-deployer.podRestarterName" . }}
