{{ if .Values.imagePullSecret }}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Values.imagePullSecret.secretName | default "dockerregistrysecret" }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}
