{{ if .Values.monitoring }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
{{ toYaml .Values.serviceMonitorLabels | indent 4 }}
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      node: {{ .Release.Name }}
  endpoints:
  - port: metrics
{{ end }}
