apiVersion: v1
kind: Service
metadata:
  name: {{ include "polkadot-deployer.rpcService" . }}
  labels:
    node: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.rpcPort }}
    name: http-rpc
  - port: {{ .Values.metricsPort }}
    name: metrics
  selector:
    node: {{ .Release.Name }}
