# Default values for bitcoind.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
terminationGracePeriodSeconds: 30
image:
  repository: ruimarinho/bitcoin-core
  tag: 0.21.0
  pullPolicy: IfNotPresent
imagePullSecrets: []
service:
  type: ClusterIP
  rpcPort: 8332
  p2pPort: 8333
  testnetPort: 18332
  testnetP2pPort: 18333
  annotations: {}

affinity: {}
nodeSelector: {}
tolerations: {}

metrics:
  enabled: true
  port: 9332
  resources:
    requests:
      memory: 64Mi
    limits:
      memory: 64Mi
      cpu: 50m

persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 300Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}
#  requests:
#    memory: 512Mi
#    cpu: 300m

# Custom bitcoind configuration file used to override default bitcoind settings
configurationFile:
  bitcoin.conf: |-
    server=1
    printtoconsole=1
    rpcuser=rpcuser
    rpcpassword=rpcpassword

electrs:
  enabled: false
  image: docker.io/interlayhq/electr:nightly-2022-03-01
  imagePullSecrets:
  pullPolicy: IfNotPresent
  network: testnet
  cors: "*"
  extraArgs: ["-vv"]
  resources: {}
    # requests:
    #   memory: 5Gi
    # limits:
    #   memory: 5Gi
    #   cpu: 2

ingress:
  enabled: false
  servicePort: 3000
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
