---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "interbtc-hydra.fullname" . }}-indexer-gateway
  labels:
    {{- include "interbtc-hydra.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "interbtc-hydra.selectorLabels" . | nindent 6 }}
      app: {{ include "interbtc-hydra.fullname" . }}
      component: indexer-gateway
  template:
    metadata:
      labels:
        {{- include "interbtc-hydra.selectorLabels" . | nindent 8 }}
        app: {{ include "interbtc-hydra.fullname" . }}
        component: indexer-gateway
    spec:
      containers:
        - name: hydra-indexer-gateway
          image: {{ .Values.hydra.gateway.image.repository }}:{{ .Values.hydra.gateway.image.tag }}
          imagePullPolicy: {{ .Values.hydra.gateway.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          envFrom:
          - secretRef:
              name: {{ .Values.hydra.gateway.dbSecretName }}
          env:
            - name: HYDRA_INDEXER_STATUS_SERVICE
              value: http://{{ include "interbtc-hydra.fullname" . }}-indexer-status/status
            - name: DEV_MODE
              value: "true"
