---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "interbtc-hydra.fullname" . }}-indexer-status
  labels:
    {{- include "interbtc-hydra.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    {{- include "interbtc-hydra.selectorLabels" . | nindent 4 }}
    app: {{ include "interbtc-hydra.fullname" . }}
    component: indexer-status
  sessionAffinity: None
  type: ClusterIP
