apiVersion: v1
kind: Service
metadata:
  name: {{ include "polkabtc.fullname" . }}-p2p
  labels:
    {{- include "polkabtc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceP2P.type }}
  ports:
    - port: {{ .Values.serviceP2P.port }}
      name: p2p
      protocol: TCP
      targetPort: {{ .Values.serviceP2P.port }}
  selector:
    {{- include "polkabtc.selectorLabels" . | nindent 4 }}
