{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "polkabtc.fullname" . }}
  labels:
    {{- include "polkabtc.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "polkabtc.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  targetLabels:
    - parachain
  endpoints:
  - port: metrics
{{- end }}
