name: polkabtc-parachain
description: Helm chart for PolkaBTC

type: application
apiVersion: v2
version: 0.2.39
appVersion: 2.0.0

home: https://interlay.io/
sources:
    - https://gitlab.com/interlay/btc-parachain
maintainers:
    - name: Interlay
      email: contact@interlay.io
